from credentials import Credentials
from users import Users
import time
import secrets
import string

def create_user(username, password):
    new_user = Users(username, password)
    return new_user

def save_users(user):
    user.save_user()

def del_user(user):
    user.delete_user()

def find_user(username):
    return Users.find_user(username)

def check_user(username):
    return Users.check_user_exist(username)

def display_user():
    return Users.display_user()

def login(username, password):
    login = Users.login(username, password)
    if login != False:
        return Users.login(username, password)

def create_credential(username, account_name, account_password):
    new_credentials = Credentials(username, account_name, account_password)
    return new_credentials

def save_credentials(credential):
    credential.save_credentials()

def del_credentials(credential):
    credential.delete_credentials()

def find_credentials(account_name):
    return Credentials.find_by_account_name(account_name)

def check_credential(account_name):
    return Credentials.check_credential_existence(account_name)

def display_credentials():
    return Credentials.display_credentials()

def main():
    name = input("Enter your name: ")

    print(f"Welcome {name}. What would you like to do?")

    while True:
        print("""Use these short codes to navigate your way through:
        1 => create account
        2 => login
        3 => list current users
        4 => exit""")

        short_code = int(input())

        if short_code == 1:
            username = input("Enter your username: ")
            password = input("Enter your password: ")

            print("Wait while we create your account...")
            time.sleep(2)
            save_users(create_user(username, password))
            print(f"""your account has been created successfully {username}
            you can now login""")

        elif short_code == 2:
            username = input("Enter your username: ")
            
            password = input("Enter your password: ")

            if login(username, password) == None:
                print("""Are you sure you have an account?
                if not please create an account...Ciao""")
            
            else:
                login(username, password)
                while True:
                    print("""Kindly use these codes to navigate through the menu items:
                    sc => show credentials
                    cc => create credentials
                    pm => go back to previous menu(exit credentials)""")
                    short_code = input().lower()

                    if short_code == "sc":
                        if display_credentials():
                            print("Getting credentials...")
                            time.sleep(3)
                            for credential in display_credentials():
                                print(f"""
                                username => {credential.username}
                                account_name => {credential.account_name} 
                                password => {credential.account_password}""")
                        
                        else:
                            print("no credentials found...:(")
                    
                    elif short_code == "cc":
                        username = input("please Enter your username: ")
                        
                        account_name = input("Enter the website name: ")

                        print("""How would you like your password?
                        1 => AutoGenerated
                        2 => Choose your password""")

                        choice = int(input())

                        if choice == 1:
                            alphabet = string.ascii_letters + string.digits
                            account_password = ''.join(secrets.choice(alphabet) for i in range(20))
                            print(f"Autogenerated password => {account_password}")

                        elif choice == 2:
                            account_password = input("Enter your password of choice: ")
                    
                        print("please wait while we create your credentials...")
                        time.sleep(3)
                        save_credentials(create_credential(username, account_name, account_password))
                        print(f"""the following credentials have been added:
                        user_name => {username}
                        account_name => {account_name}
                        account_password => {account_password}""")
                    
                    elif short_code == "pm":
                        break

                    else:
                        print("Kindly use the short codes provided")
        
        elif short_code == 3:
            print("Wait while we get you the users...")
            time.sleep(2)
            if display_user():
                for user in display_user():
                    print(f"{user.username}")
            
            else:
                print("found no users. add one?;)")
        
        elif short_code == 4:
            print(f"It was nice meeting you {name}...Bye")
            break

        else:
            print(f"kindly use the short codes provided {name}")

if __name__ == "__main__":
    main()